### ISSUE TITLE
Hack20

### ISSUE THREAD

**Issue by orestesgaolin** [dhy3y/DartSmart#1]
Hi, I just wanted to let you know that I noticed that you had issues with adding youtube link to the submission and fixed it manually, so that you're accepted into the first round of voting.

**Comment by dhy3y** [comment]
> 
> 
> Hi, I just wanted to let you know that I noticed that you had issues with adding youtube link to the submission and fixed it manually, so that you're accepted into the first round of voting.


Thank you so much! @orestesgaolin
